name: irp-air-pollution
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.0.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - fqdn=1.5.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.2
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - libcxx=16.0.6
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.44.0
  - libzlib=1.2.13
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - nbclient=0.8.0
  - nbconvert=7.11.0
  - nbconvert-core=7.11.0
  - nbconvert-pandoc=7.11.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - openssl=3.1.4
  - overrides=7.4.0
  - packaging=23.2
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - prometheus_client=0.18.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyobjc-core=10.0
  - pyobjc-framework-cocoa=10.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qtconsole-base=5.5.0
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.12.0
  - send2trash=1.8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.13.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.9
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - wheel=0.41.3
  - widgetsnbextension=4.0.9
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - boto3==1.28.83
      - botocore==1.31.83
      - cachetools==5.3.2
      - catboost==1.2.2
      - certifi==2023.7.22
      - contourpy==1.2.0
      - cryptography==41.0.5
      - cycler==0.12.1
      - cython==3.0.5
      - flatbuffers==23.5.26
      - fonttools==4.44.0
      - gast==0.5.4
      - google-auth==2.23.4
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.2
      - h5py==3.10.0
      - jmespath==1.0.1
      - joblib==1.3.2
      - keras==2.15.0
      - keras-nightly==2.15.0.dev2023092207
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - matplotlib==3.8.1
      - ml-dtypes==0.3.1
      - mock==5.1.0
      - moto==4.2.7
      - numpy==1.26.1
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - pandas==2.1.2
      - patsy==0.5.3
      - pillow==10.1.0
      - plotly==5.18.0
      - pmdarima==2.0.4
      - protobuf==4.23.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-graphviz==0.20.1
      - requests-oauthlib==1.3.1
      - responses==0.24.0
      - rsa==4.9
      - s3transfer==0.7.0
      - scikeras==0.12.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.13.0
      - statsmodels==0.14.0
      - tb-nightly==2.15.0a20231023
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - tensorflow-metal==1.1.0
      - termcolor==2.3.0
      - tf-estimator-nightly==2.14.0.dev2023080308
      - tf-nightly==2.16.0.dev20231018
      - tf-nightly-macos==2.16.0.dev20231018
      - threadpoolctl==3.2.0
      - tzdata==2023.3
      - urllib3==1.26.18
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - xgboost==2.0.1
      - xmltodict==0.13.0
