name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alabaster=0.7.12
  - anaconda-client=1.11.0
  - anaconda-project=0.11.1
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.2
  - atomicwrites=1.4.0
  - automat=20.2.0
  - autopep8=1.6.0
  - autovizwidget=0.21.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.11.1
  - binaryornot=0.4.4
  - bitarray=2.5.1
  - bkcharts=0.2
  - black=22.6.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.0
  - boltons=23.0.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - clyent=1.2.2
  - colorcet=3.0.0
  - conda=23.3.1
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - conda-token=0.4.0
  - constantly=15.1.0
  - cssselect=1.1.0
  - curl=7.84.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - cython=0.29.32
  - cytoolz=0.11.0
  - daal4py=2021.6.0
  - dal=2021.6.0
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - datashader=0.14.1
  - datashape=0.5.4
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2022.7.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - expat=2.4.9
  - fftw=3.3.9
  - filelock=3.6.0
  - flake8=4.0.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.7.1
  - gensim=4.1.2
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=1.1.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - hdijupyterutils=0.21.0
  - heapdict=1.0.1
  - holoviews=1.15.0
  - hvplot=0.8.0
  - hyperlink=21.0.0
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - imagesize=1.4.1
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.5
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - jdcal=1.4.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jellyfish=0.9.0
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jupyter=1.0.0
  - jupyter_console=6.4.3
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.4.0
  - kiwisolver=1.4.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.6.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcurl=7.84.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libidn2=2.3.2
  - liblief=0.11.5
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.46.0
  - libntlm=1.4
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzopfli=1.0.3
  - llvmlite=0.38.0
  - locket=1.0.0
  - lz4=3.1.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markdown=3.3.4
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - msgpack-python=1.0.3
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclient=0.5.13
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.4
  - nltk=3.7
  - nose=1.3.7
  - nspr=4.33
  - nss=3.74
  - numba=0.55.1
  - numexpr=2.8.3
  - numpydoc=1.4.0
  - olefile=0.46
  - oniguruma=6.9.7.1
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=2.1.2
  - pandocfilters=1.5.0
  - panel=0.13.1
  - param=1.12.0
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - patch=2.7.6
  - patchelf=0.13
  - pathspec=0.9.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pkginfo=1.8.2
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.20
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure-sasl=0.6.2
  - py=1.11.0
  - py-lief=0.11.5
  - pyarrow==13.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.8.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pyct=0.4.8
  - pycurl=7.45.1
  - pydispatcher=2.0.5
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.4.0
  - pyhamcrest=2.0.2
  - pyhive=0.7.0
  - pyls-spyder=0.4.0
  - pyodbc=4.0.34
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pyspnego=0.9.2
  - pytables=3.6.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.5.0
  - python-slugify=5.0.2
  - python-snappy=0.6.0
  - python_abi=3.10
  - pytz=2022.1
  - pyviz_comms=2.0.2
  - pywavelets=1.3.0
  - pyxdg=0.27
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.0.3
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - queuelib=1.5.0
  - readline=8.1.2
  - regex=2022.7.9
  - requests-file=1.5.1
  - requests-kerberos=0.14.0
  - ripgrep=13.0.0
  - rope=0.22.0
  - rtree=0.9.7
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.100
  - sasl=0.3.1
  - scikit-image=0.19.2
  - scikit-learn=1.0.1
  - scikit-learn-intelex=2021.6.0
  - scrapy=2.6.2
  - seaborn=0.11.2
  - secretstorage=3.3.1
  - service_identity=18.1.0
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sparkmagic=0.20.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.3.3
  - spyder-kernels=2.3.3
  - sqlalchemy=1.4.39
  - sqlite=3.39.3
  - statsmodels=0.13.2
  - sympy=1.10.1
  - tabulate=0.8.10
  - tbb=2021.6.0
  - tbb4py=2021.6.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.13.1
  - testpath=0.6.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - thrift=0.17.0
  - thrift_sasl=0.4.3
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.12
  - tldextract=3.2.0
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.11.2
  - tqdm=4.64.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - unidecode=1.2.0
  - unixodbc=2.3.11
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wget=1.21.3
  - whatthepatch=1.0.2
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xarray=0.20.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.3
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.1.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.15.2
  - zstd=1.5.2
  - pip:
      - astroid==3.0.0
      - astropy==5.3.4
      - asttokens==2.4.0
      - attrs==23.1.0
      - awscli==1.29.63
      - blinker==1.6.3
      - bokeh==3.3.0
      - boto3==1.28.63
      - botocore==1.31.63
      - catboost==1.2.2
      - click==8.1.7
      - cloudpickle==2.2.1
      - colorama==0.4.4
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - cookiecutter==2.4.0
      - cryptography==41.0.4
      - dill==0.3.7
      - docker==6.1.3
      - docutils==0.16
      - dparse==0.6.3
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - flask==3.0.0
      - fqdn==1.5.1
      - future==0.18.3
      - google-pasta==0.2.0
      - gssapi==1.8.3
      - incremental==22.10.0
      - ipython==8.16.1
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.4.0
      - jupyter-core==5.4.0
      - jupyter-events==0.7.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - keras==2.15.0
      - keras-tuner==1.4.6
      - krb5==0.5.1
      - lief==0.13.2
      - lxml==4.9.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multiprocess==0.70.15
      - nbclassic==1.0.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - notebook==6.5.6
      - notebook-shim==0.2.3
      - numpy==1.26.0
      - overrides==7.4.0
      - pathos==0.3.1
      - pillow==10.0.1
      - pip==23.2.1
      - pmdarima==2.0.4
      - pox==0.3.3
      - ppft==1.7.6.7
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - pure-eval==0.2.2
      - pyarrow==13.0.0
      - pyfunctional==1.4.3
      - pygments==2.16.1
      - pylint==3.0.1
      - pyopenssl==23.2.0
      - pyqt5-sip==12.11.0
      - pytest==7.4.2
      - python-json-logger==2.0.7
      - pyyaml==6.0
      - pyzmq==25.1.1
      - referencing==0.30.2
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.10.6
      - rsa==4.7.2
      - s3fs==0.4.2
      - s3transfer==0.7.0
      - sagemaker==2.192.0
      - sagemaker-data-insights==0.3.3
      - sagemaker-datawrangler==0.4.3
      - sagemaker-scikit-learn-extension==2.5.0
      - sagemaker-studio-analytics-extension==0.0.20
      - sagemaker-studio-sparkmagic-lib==0.1.4
      - schema==0.7.5
      - scipy==1.11.3
      - send2trash==1.8.2
      - setuptools==68.2.2
      - smclarify==0.5
      - smdebug-rulesconfig==1.0.1
      - stack-data==0.6.3
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tinycss2==1.2.1
      - tornado==6.3.3
      - traitlets==5.11.2
      - twisted==23.8.0
      - ujson==5.8.0
      - uri-template==1.3.0
      - urllib3==2.0.6
      - webcolors==1.13
      - werkzeug==3.0.0
      - wheel==0.41.2
      - xgboost==2.0.1
      - xyzservices==2023.10.0
